/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-01 18:08:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.*;
import com.project.harubang.user.*;

public final class mypageFriendAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682261928999L));
    _jspx_dependants.put("jar:file:/C:/Users/ehdrm/Desktop/harubangP%20(4)/harubangP/apache-tomcat-9.0.76/wtpwebapps/harubang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.project.harubang.user");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\r\n");

	String friendId=(String)request.getSession().getAttribute("friendId"); 
	String id=(String)request.getSession().getAttribute("id");
 	List<UserVO> List =  (List<UserVO>)request.getSession().getAttribute("List");
 	List<UserVO> RECIVE_List = (List<UserVO>)request.getSession().getAttribute("RECIVE_List");

      out.write("<!DOCTYPE html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.4.10/dist/sweetalert2.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.4.10/dist/sweetalert2.min.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("const Toast = Swal.mixin({\r\n");
      out.write("    toast: true,\r\n");
      out.write("    position: 'center-center',\r\n");
      out.write("    showConfirmButton: false,\r\n");
      out.write("    timer: 1000,\r\n");
      out.write("    timerProgressBar: true,\r\n");
      out.write("    didOpen: (toast) => {\r\n");
      out.write("        toast.addEventListener('mouseenter', Swal.stopTimer);\r\n");
      out.write("        toast.addEventListener('mouseleave', Swal.resumeTimer);\r\n");
      out.write("    },\r\n");
      out.write("    didClose: () => {\r\n");
      out.write("\r\n");
      out.write("    	setTimeout(() => {\r\n");
      out.write("            location.href = \"/user/mypage\";\r\n");
      out.write("        }, 200);\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("	$(function(){\r\n");
      out.write("		getFriendPage();\r\n");
      out.write("		getFriendRecive();\r\n");
      out.write("		getFriendList();\r\n");
      out.write("		getFriendList2();\r\n");
      out.write("    }); \r\n");
      out.write("	\r\n");
      out.write("	function friend() {\r\n");
      out.write("		\r\n");
      out.write("		if ($(\"#friend\").val() == \"\") {\r\n");
      out.write("\r\n");
      out.write("			$(\"#friend\").focus();\r\n");
      out.write("			var friendList=\"\";\r\n");
      out.write("			friendList = \"<p class='friendNot'>* 아이디를 입력해주세요. </p>\"\r\n");
      out.write("			$(\".requestWrap\").html(friendList);\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if ($(\"#friend\").val() == \"");
      out.print(id);
      out.write("\") {\r\n");
      out.write("			\r\n");
      out.write("			$(\"#friend\").focus();\r\n");
      out.write("			var friendList=\"\";\r\n");
      out.write("			friendList = \"<p class='friendNot'>* 사용자 아이디와 동일합니다. </p>\"\r\n");
      out.write("			$(\".requestWrap\").html(friendList);\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friend\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"id\" : $(\"#friend\").val(),\r\n");
      out.write("			},success : function(result) {\r\n");
      out.write("				if(result==\"F\"){\r\n");
      out.write("					if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fail2==\"fail\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("					var friendList=\"\";\r\n");
      out.write("					friendList = \"<p class='friendNot'>* 존재하지않는 아이디 입니다</p>\"\r\n");
      out.write("					$(\".requestWrap\").html(friendList);\r\n");
      out.write("					}\r\n");
      out.write("				}else {\r\n");
      out.write("					var friendList= result;\r\n");
      out.write("					friendList  = \"<div class='friendRequest'>\";\r\n");
      out.write("					friendList += '<img class=\"item\" src=\"/resources/images/icon/profile-user.png\" alt=\"\">';\r\n");
      out.write("					friendList += '<h5 class=\"item\">'+result+'</h5>';\r\n");
      out.write("					friendList += \"<input type='button' class='item' id='friendRequest'  value='요청' onclick='friendRequest()'>\";\r\n");
      out.write("					friendList += \"</div>\";\r\n");
      out.write("					$(\".requestWrap\").html(friendList);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function friendRequest() {\r\n");
      out.write("		\r\n");
      out.write("		  const btnElement = document.getElementById('friendRequest');\r\n");
      out.write("		  btnElement.value = \"요청중\";\r\n");
      out.write("		   \r\n");
      out.write("		  $.ajax({\r\n");
      out.write("				dataType : \"text\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				url : \"/friendRequest\"\r\n");
      out.write("				,success : function(result) {\r\n");
      out.write("					if(result==\"F\"){\r\n");
      out.write("\r\n");
      out.write("						Toast.fire({\r\n");
      out.write("						    icon: 'success',\r\n");
      out.write("						    title: '친구요청이 되었습니다.',\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("					}else {\r\n");
      out.write("						var friendList=\"\";\r\n");
      out.write("						friendList = \"<p class='friendNot'>* 이미 요청중이거나 친구목록에 있는 친구입니다</p>\"\r\n");
      out.write("						$(\".requestWrap\").html(friendList);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	function getFriendPage() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"JSON\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendRequesting\",\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				for(var i=0; i<result.length; i++){\r\n");
      out.write("					var obj = result[i];\r\n");
      out.write("					console.log(obj);\r\n");
      out.write("					friendList = \"<div class='friendRequest recive_id\"+i+\"' 'item'>\";\r\n");
      out.write("					friendList += '<img class=\"item\" src=\"/resources/images/icon/profile-user.png\" alt=\"\">';\r\n");
      out.write("					friendList += '<h5 class=\"item\">' + obj['recive_id'] + '</h5>';\r\n");
      out.write("					friendList += '<input class=\"item\" type=\"button\" value=\"요청중\" onclick=\"requesting1('+i+')\">';\r\n");
      out.write("					friendList += '</div>';\r\n");
      out.write("					$(\".requestList\").append(friendList);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function requesting1(i) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/requestCancel\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"recive_id\"  : $(\".recive_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					Toast.fire({\r\n");
      out.write("					    icon: 'success',\r\n");
      out.write("					    title: '친구요청이 취소되었습니다.',\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}) \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function getFriendRecive() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"JSON\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendRecive\",\r\n");
      out.write("			success : function(result1) {\r\n");
      out.write("				var html = \"\";\r\n");
      out.write("				for(var i=0; i<result1.length; i++){\r\n");
      out.write("					var obj = result1[i];\r\n");
      out.write("					html +=\"<div class='friendRequest send_id\"+i+\"'>\"\r\n");
      out.write("					html +=\"<img class='item' src='/resources/images/icon/profile-user.png' alt=''>\"\r\n");
      out.write("					html +=\"<h5 class='item'>\"+obj['send_id']+\"</h5>\"\r\n");
      out.write("					html +=\"<input class='item' type='button' value='수락' onclick='acceptFriend(\"+i+\")'>\"\r\n");
      out.write("					html +=	\"<input class='item' type='button' value='거절' onclick='refuseFriend(\"+i+\")'>\"\r\n");
      out.write("					html += \"</div>\"\r\n");
      out.write("				}\r\n");
      out.write("				document.getElementById(\"friendRecive\").innerHTML = html;\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function acceptFriend(i) {\r\n");
      out.write("		\r\n");
      out.write(" 		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/acceptFriend\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"send_id\"  : $(\".send_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					Toast.fire({\r\n");
      out.write("					    icon: 'success',\r\n");
      out.write("					    title: '친구 추가 완료중.',\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	function refuseFriend(i) {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/refuseFriend\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"send_id\"  : $(\".send_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					Toast.fire({\r\n");
      out.write("					    icon: 'success',\r\n");
      out.write("					    title: '친구 거절 신천중.',\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}) \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function getFriendList() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"JSON\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendList\",\r\n");
      out.write("			success : function(result2) {\r\n");
      out.write("				for(var i=0; i<result2.length; i++){\r\n");
      out.write("					var obj = result2[i];\r\n");
      out.write("					friendList =    \"<div class='friendRequest' 'send_id\"+i+\"'>\"\r\n");
      out.write("					friendList +=   '<img class=\"item\" src=\"/resources/images/icon/profile-user.png\" alt=\"\">'\r\n");
      out.write("					friendList +=   '<h5 class=\"item\">'+obj['send_id'] +'</h5>'\r\n");
      out.write("					friendList +=   '<input class=\"item\" type=\"button\" value=\"구경하기\"  onclick=\"friendWatch2('+i+')\" >'\r\n");
      out.write("					friendList +=   '<input class=\"item\" type=\"button\" value=\"삭제\"  onclick=\"friendCencle2('+i+')\" >'\r\n");
      out.write("					friendList +=   \"</div>\"\r\n");
      out.write("					$(\".getFriendList\").append(friendList);\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})	\r\n");
      out.write("	}\r\n");
      out.write("	function friendCencle2(i) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendCencle2\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"send_id\"  : $(\".send_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"삭제 실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					Toast.fire({\r\n");
      out.write("					    icon: 'success',\r\n");
      out.write("					    title: '친구 삭제 중입니다.',\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}) \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/* 	function friendWatch2(i) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendWatch2\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"send_id\"  : $(\".send_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"삭제 실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}) \r\n");
      out.write("	} */\r\n");
      out.write("	\r\n");
      out.write("	function getFriendList2() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"JSON\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendList2\",\r\n");
      out.write("			success : function(result3) {\r\n");
      out.write("				for(var i=0; i<result3.length; i++){\r\n");
      out.write("					var obj= result3[i]\r\n");
      out.write("					friendList =   \"<div class='friendRequest' 'recive_id\"+i+\"'>\"\r\n");
      out.write("					friendList +=  '<img class=\"item\" src=\"/resources/images/icon/profile-user.png\" alt=\"\">'\r\n");
      out.write("					friendList +=  '<h5 class=\"item\">'+obj['recive_id'] +'</h5>'\r\n");
      out.write("					friendList +=  '<input class=\"item\" type=\"button\" value=\"구경하기\"  onclick=\"friendWatch('+i+')\" >'\r\n");
      out.write("					friendList +=  '<input class=\"item\" type=\"button\" value=\"삭제\"  onclick=\"friendCencle('+i+')\" >'\r\n");
      out.write("					friendList +=  \"</div>\"\r\n");
      out.write("					$(\".getFriendList2\").append(friendList);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function friendCencle(i) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendCencle\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"recive_id\"  : $(\".recive_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"삭제 실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					Toast.fire({\r\n");
      out.write("					    icon: 'success',\r\n");
      out.write("					    title: '친구 삭제 중입니다.',\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}) \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/* 	function friendWatch(i) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			dataType : \"text\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/friendWatch\",\r\n");
      out.write("			data : {\r\n");
      out.write("				\"recive_id\"  : $(\".recive_id\"+i).text()\r\n");
      out.write("			},\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				if(result == \"T\"){\r\n");
      out.write("					alert(\"삭제 실패.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					\r\n");
      out.write("					location.href=\"구경하는 페이지로 가기\";\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}) \r\n");
      out.write("	} */\r\n");
      out.write("</script>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>하루방</title>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mypageFriendAdd.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"topMenuWrap\">\r\n");
      out.write("         <h2>친구 추가·목록</h2>\r\n");
      out.write("         <div class=\"menuWrap\">\r\n");
      out.write("             <ul>\r\n");
      out.write("                 <li><div class=\"myImg\"></div></li>\r\n");
      out.write("                 <li>");
      out.print(id );
      out.write(" ▼</li>\r\n");
      out.write("                 <li><img src=\"/resources/images/icon/notification.png\" alt=\"\"></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"searchWrap\">\r\n");
      out.write("         <input class=\"searchID\" id=\"friend\" type=\"text\" placeholder=\"아이디를 검색하세요.\">\r\n");
      out.write("         <input class=\"searchButton\" type=\"button\" value=\"검색\" onclick=\"friend()\">\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"requestWrap\" >\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"friendListWrap\">\r\n");
      out.write("         <h3>친구 목록</h3>\r\n");
      out.write("         <div class=\"frienList getFriendList getFriendList2\">\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"friendListWrap\">\r\n");
      out.write("         <h3>친구 (수락 : 거절) </h3>\r\n");
      out.write("         <div class=\"frienList\" id=\"friendRecive\">\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"requestListWrap\">\r\n");
      out.write("         <h3>요청중인 친구목록</h3>\r\n");
      out.write("         <div class=\"requestList\" >\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
