/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-10-30 11:47:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.schedule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.project.harubang.info.InfoDTO;
import java.awt.SystemColor;
import java.util.ArrayList;
import com.project.harubang.info.InfoResultVO;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ehdrm/Desktop/하루방/apache-tomcat-9.0.76/wtpwebapps/harubang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682261928999L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.harubang.info.InfoResultVO");
    _jspx_imports_classes.add("com.project.harubang.info.InfoDTO");
    _jspx_imports_classes.add("java.awt.SystemColor");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	ArrayList<InfoResultVO> Infolist = (ArrayList<InfoResultVO>)request.getAttribute("infoList");
	ArrayList<InfoDTO> Infolist1 = (ArrayList<InfoDTO>)request.getAttribute("infoList");

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>하루방</title>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Swiper_3.3.1_css_swiper.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/schedule.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/grid-swiper.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 공통 Top 구조 include  -->	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/top.jsp", out, false);
      out.write("<!-- Banner Type  -->\r\n");
      out.write("	<div class=\"bannerWrap\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/default/banner_jeju01.png\" alt=\"제주이미지\" class=\"bn\">\r\n");
      out.write("        <div class=\"titleWrap\">\r\n");
      out.write("            <h4>Make A Day In Jeju</h4>\r\n");
      out.write("            <h2>나의여행</h2>\r\n");
      out.write("            <div class=\"button\"><input type=\"button\" value=\"일정 만들기\" onClick=\"location.href='/schedule/makeSchedule'\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Search & menu Wrap -->\r\n");
      out.write("    <div class=\"searchWrap\">\r\n");
      out.write("        <h2>하루방에서 나의 일정을 만들어보세요.</h2>\r\n");
      out.write("        <p>검색하거나 목록에서 직접 선택해주세요.</p>\r\n");
      out.write("        <div class=\"searchBar\">\r\n");
      out.write("            <input class=\"serchInput\" type=\"text\"><br>\r\n");
      out.write("            <input type=\"button\" class=\"button-add\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <nav class=\"menuWrap\">\r\n");
      out.write("            <ul class=\"clearfix\">\r\n");
      out.write("                <li class=\"active\">나의 일정</li>                \r\n");
      out.write("                <li>찜목록</li>                \r\n");
      out.write("                <li>나의 기록</li>                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("        <!-- 나의 일정 목록 보여주기  -->\r\n");
      out.write("    <div class=\"swiperWrap\">\r\n");
      out.write("        <div class=\"swiper-container\">\r\n");
      out.write("            <div class=\"swiper-wrapper\">\r\n");
      out.write(" \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/Swiper_3.3.1_js_swiper.min.js\"></script>\r\n");
      out.write("    ");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/gird_swiper_schedule.js\"></script>\r\n");
      out.write("     <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/schedule.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("        $(\".menuWrap li\").click(function(){\r\n");
      out.write("     		\r\n");
      out.write("            let i =  $(this).index()\r\n");
      out.write("            $(\".menuWrap li\").removeClass(\"active\")\r\n");
      out.write("            $(\".menuWrap li\").eq(i).addClass(\"active\")\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("/*      	$(function(){\r\n");
      out.write("     		heartList();\r\n");
      out.write("	    });\r\n");
      out.write("		\r\n");
      out.write("		function heartList() {\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("	    		dataType : \"JSON\",\r\n");
      out.write("	    		url : \"/heartList\",\r\n");
      out.write("	    		type : \"POST\",\r\n");
      out.write("	    		data : {\r\n");
      out.write("	    		},success : function(result) {\r\n");
      out.write("	    	 	   for(var i=0;i<result.length;i++){\r\n");
      out.write("	    	 		   var obj = result[i];\r\n");
      out.write("	    	 		   var wish = obj['wish']\r\n");
      out.write("	    	 		   var classid = obj['checkId']\r\n");
      out.write("	    	 		  	if(wish==\"SUCCESS\"){\r\n");
      out.write("	    	 		  		$('#'+classid).attr(\"src\", \"/resources/images/icon/heartR.png\");\r\n");
      out.write("	    	 		  	}\r\n");
      out.write("	    	 	   }\r\n");
      out.write("				}\r\n");
      out.write("				}\r\n");
      out.write("	    	})\r\n");
      out.write("		}\r\n");
      out.write("		 */\r\n");
      out.write("		$(function(){\r\n");
      out.write("			myScheduleList();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function myScheduleList() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				url : \"/schedule/myScheduleList\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				success : function (myresult) {\r\n");
      out.write("					var innerHtml = \"\";\r\n");
      out.write("					for (var i = 0 ; i < myresult.length; i++){ \r\n");
      out.write("						var obj = myresult[i];\r\n");
      out.write("						var detail = JSON.parse(obj['detailSchedule']);\r\n");
      out.write("						var dateKey = Object.keys(detail);\r\n");
      out.write("						/* 일정 설명 */\r\n");
      out.write("						if((dateKey.length-1) == 0){\r\n");
      out.write("							var dayCount = \"당일치기\";\r\n");
      out.write("						}else{\r\n");
      out.write("							var dayCount = (dateKey.length-1) + \"박 \" +dateKey.length + \"일\";\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("						/* 이미지 명 받기 */\r\n");
      out.write("						var imgname = detail[dateKey[0]][0]['imgFile'];\r\n");
      out.write("						innerHtml += '<div id=\"'+ obj['scheduleNumber'] +'\" class=\"swiper-slide\" data-filter=\"schedule\" onclick=\"lookMyScehdule(\\'' + obj['id'] + '\\', this.id)\">';\r\n");
      out.write("						innerHtml += '<img class=\"mainImg\" src=\"'+imgname+'\" alt=\"\">';\r\n");
      out.write("						innerHtml += '<div class=\"tWrap\">';\r\n");
      out.write("						innerHtml += '<h4>'+ obj['scheduleName'] +'</h4>';\r\n");
      out.write("						innerHtml += '<p>'+ dayCount+'</p>';\r\n");
      out.write("						innerHtml += '</div>';\r\n");
      out.write("						innerHtml += '</div>';	\r\n");
      out.write("						$(\".swiper-wrapper\").html(innerHtml);\r\n");
      out.write("					}\r\n");
      out.write("					var swiper = new Swiper(\".swiper-container\", {\r\n");
      out.write("					    slidesPerView: 4,\r\n");
      out.write("					    slidesPerGroup : 4,\r\n");
      out.write("					    slidesPerColumn: 3,\r\n");
      out.write("					    grid: {\r\n");
      out.write("					        rows: 3,\r\n");
      out.write("					    },\r\n");
      out.write("					    spaceBetween: 30,\r\n");
      out.write("					    pagination: {\r\n");
      out.write("					        el: \".swiper-pagination\",\r\n");
      out.write("					        clickable: true,\r\n");
      out.write("					    },\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("    </script>\r\n");
      out.write("	<!-- 공통 Footer 구조 include  -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
