/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-03 01:29:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.project.harubang.board.BoardServiceImpl;
import com.project.harubang.board.BoardService;
import com.project.harubang.board.BoardVO;
import com.project.harubang.board.BoardMapper;

public final class getBoardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/ehdrm/Desktop/harubangP%20(4)/harubangP/apache-tomcat-9.0.76/wtpwebapps/harubang/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682261928999L));
    _jspx_dependants.put("jar:file:/C:/Users/ehdrm/Desktop/harubangP%20(4)/harubangP/apache-tomcat-9.0.76/wtpwebapps/harubang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.project.harubang.board.BoardServiceImpl");
    _jspx_imports_classes.add("com.project.harubang.board.BoardService");
    _jspx_imports_classes.add("com.project.harubang.board.BoardVO");
    _jspx_imports_classes.add("com.project.harubang.board.BoardMapper");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\" integrity=\"sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");

	List<BoardVO> boardList = (List)request.getAttribute("boardList");

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>::게시판 목록::</title>\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200;300;400;500;600;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Swiper_3.3.1_css_swiper.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/getBoardList.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board.css\" rel=\"stylesheet\"/>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 공통 Top 구조 include  -->	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/top.jsp", out, false);
      out.write("<!-- Banner Type  -->\r\n");
      out.write("	<div class=\"bannerWrap\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/default/banner_jeju03.png\" alt=\"제주이미지\" class=\"bn\">\r\n");
      out.write("        <div class=\"titleWrap\">\r\n");
      out.write("            <h4>board</h4>\r\n");
      out.write("            <h2>게시판</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("	<!-- 게시판 시작  -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class = \"h2\">게시판 목록</h2>\r\n");
      out.write("	\r\n");
      out.write("		<div class = \"menuWrap\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>전체</li>&nbsp&nbsp\r\n");
      out.write("				<li>자유 게시판</li>&nbsp&nbsp\r\n");
      out.write("				<li>QnA 게시판</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	<!-- 검색 부분 -->\r\n");
      out.write("      <form action=\"getBoardListGo\" method=\"post\">\r\n");
      out.write("         <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"700\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td align=\"right\"><select name=\"searchCondition\">\r\n");
      out.write("                     <option value=\"TITLE\">제목\r\n");
      out.write("                     <option value=\"CONTENT\">내용\r\n");
      out.write("               </select> <input name=\"searchKeyword\" type=\"text\"> <input type=\"submit\"\r\n");
      out.write("                  value=\"Search\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("      <!-- 글 리스트 부분 -->\r\n");
      out.write("		<table class=\"tableBL\" border=\"0.5\" cellpadding=\"0\" cellspacing=\"0\" width=\"700\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th bgcolor=\"orange\" width=\"100\">번호</th>\r\n");
      out.write("				<th bgcolor=\"orange\" width=\"200\">제목</th>\r\n");
      out.write("				<th bgcolor=\"orange\" width=\"150\">작성자</th>\r\n");
      out.write("				<th bgcolor=\"orange\" width=\"150\">등록일</th>\r\n");
      out.write("				<th bgcolor=\"orange\" width=\"100\">조회수</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("	  		");
 
				for (BoardVO board : boardList) {
			
      out.write("<tr id=\"category\" data-filter=\"");
      out.print(board.getBcategory());
      out.write("\">\r\n");
      out.write("				<td>");
      out.print(board.getSeq());
      out.write("</td>\r\n");
      out.write("				<td align=\"left\"><a href=\"/getBoardGo?seq=");
      out.print(board.getSeq());
      out.write("\">\r\n");
      out.write("						");
      out.print(board.getTitle());
      out.write("</a></td>\r\n");
      out.write("				<td>");
      out.print(board.getId());
      out.write("</td>\r\n");
      out.write("				<td>");
      //  fmt:formatDate
      org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
      boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
      try {
        _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatDate_005f0.setParent(null);
        // /WEB-INF/views/board/getBoardList.jsp(81,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setValue(board.getWritedate());
        // /WEB-INF/views/board/getBoardList.jsp(81,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
        int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
        if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
        _jspx_th_fmt_005fformatDate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
      }
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(board.getCnt());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				}
			
      out.write("</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<a href=\"/insertBoard\" class=\"button1\">새글 등록</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 공통 Footer 구조 include  -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("<!-- Script 부분 -->\r\n");
      out.write("    <script>\r\n");
      out.write("	$(\".menuWrap ul li\").on(\"click\", function(){\r\n");
      out.write("		var filter = $(this).html().toLowerCase();\r\n");
      out.write("		if(filter == \"자유 게시판\"){\r\n");
      out.write("			filter = \"자유\";\r\n");
      out.write("		} else if(filter == \"QnA 게시판\"){\r\n");
      out.write("			filter = \"QnA\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(filter == \"자유\"){\r\n");
      out.write("		          $(\"[data-filter='QnA']\").removeClass(\"category\").hide();\r\n");
      out.write("		       	  $(\"[data-filter='자유']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		          $(\"[data-filter='동행']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		          $(\"[data-filter='긴급']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		    } else if (filter == \"전체\"){\r\n");
      out.write("		       	  $(\"[data-filter='자유']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		          $(\"[data-filter='동행']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		          $(\"[data-filter='긴급']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("			      $(\"[data-filter='QnA']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		    } else{\r\n");
      out.write("		         $(\".category\").not(\"[data-filter='\"+filter+\"']\").removeClass(\"category\").hide();\r\n");
      out.write("		         $(\"[data-filter='QnA']\").addClass(\"category\").attr(\"style\", null).show();\r\n");
      out.write("		    }\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
