/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-10-30 11:47:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class toolBlog1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ehdrm/Desktop/하루방/apache-tomcat-9.0.76/wtpwebapps/harubang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682261928999L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 	
	String name =(String)request.getSession().getAttribute("id"); 

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Dongle&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Dongle&family=Jua&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200;300;400;500;600;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lisu+Bosa:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poor+Story&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\" integrity=\"sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../../../resources/ckeditor/contents.css\">\r\n");
      out.write("	<meta charset=\"UTF-8\" />\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("	   body, html {\r\n");
      out.write("		  margin: 0;\r\n");
      out.write("		  padding: 0;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* Common styles for buttons */\r\n");
      out.write("		a[href=\"goBlog\"], a.main {\r\n");
      out.write("		  font-family: 'Dongle', sans-serif;\r\n");
      out.write("		  display: inline-block;\r\n");
      out.write("		  padding: 10px 20px;\r\n");
      out.write("		  font-size: 18px;\r\n");
      out.write("		  background-color: skyblue;\r\n");
      out.write("		  color: #fff;\r\n");
      out.write("		  text-decoration: none;\r\n");
      out.write("		  border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* Blog creation button */\r\n");
      out.write("		a[href=\"goBlog\"] {\r\n");
      out.write("		  float: right;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* Main screen button */\r\n");
      out.write("		a.main {\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  bottom: 30px;\r\n");
      out.write("		  right: 30px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* Flex container for items */\r\n");
      out.write("		.flex_column {\r\n");
      out.write("		  display: flex;\r\n");
      out.write("		  flex-direction: column;\r\n");
      out.write("		  width: 1020px;\r\n");
      out.write("		  margin: 0 auto;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 메인화면 버튼 기본 스타일 */\r\n");
      out.write("		a.main {\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		justify-content:center;\r\n");
      out.write("		position:absoulte;\r\n");
      out.write("		width:80px;\r\n");
      out.write("		margin:0 auto;\r\n");
      out.write("         font-family: 'Dongle', sans-serif;\r\n");
      out.write("		  display: inline-block;\r\n");
      out.write("		  padding: 10px 20px;\r\n");
      out.write("		  font-size: 18px; /* 폰트 크기 (원하는 크기로 조정해주세요) */\r\n");
      out.write("		  background-color: skyblue; /* 버튼 배경색 (여기서는 파란색을 사용했습니다) */\r\n");
      out.write("		  color: #fff; /* 버튼 텍스트 색상 (여기서는 흰색을 사용했습니다) */\r\n");
      out.write("		  text-decoration: none;\r\n");
      out.write("		  border-radius: 5px; /* 버튼 테두리를 둥글게 만듭니다 */\r\n");
      out.write("		  position: absolute; /* 버튼을 절대 위치로 설정합니다 */\r\n");
      out.write("		  bottom: -100%; /* 버튼을 부모 요소의 아래쪽에 배치합니다 */\r\n");
      out.write("		  right: 50%; /* 버튼을 부모 요소의 오른쪽에 배치합니다 */\r\n");
      out.write("		  margin: 0 auto;\r\n");
      out.write("		  \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("        .lineBox{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            margin-bottom: 50px;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 350px;\r\n");
      out.write("        }\r\n");
      out.write("        .itemBox{\r\n");
      out.write("        	cursor:pointer;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width:250px;\r\n");
      out.write("            height:350px;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            border-radius:20px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            -webkit-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("            -moz-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("            -ms-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("            -o-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("        }\r\n");
      out.write("        .itemBox img{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:350px;\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("        }\r\n");
      out.write("        .topSide{\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .bottomSide{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            bottom:0;\r\n");
      out.write("            left:0;\r\n");
      out.write("            padding:0.75rem 0.75rem 0.5rem 1rem;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("        .bottomSide .title{\r\n");
      out.write("            font-weight:bold;\r\n");
      out.write("            font-size:35px;\r\n");
      out.write("            padding-top:5px;\r\n");
      out.write("            padding-right:15px;\r\n");
      out.write("            font-family: 'Dongle', sans-serif;\r\n");
      out.write("            font-family: 'Jua', sans-serif;\r\n");
      out.write("            font-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("        }\r\n");
      out.write("        .bottomSide .id{\r\n");
      out.write("            padding-top:7px;\r\n");
      out.write("            font-size:25px;\r\n");
      out.write("            font-family: 'Dongle', sans-serif;\r\n");
      out.write("            margin-bottom:-15px;\r\n");
      out.write("        }\r\n");
      out.write("        .bottomSide .date{\r\n");
      out.write("            padding-bottom:8px;\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            font-family: 'Dongle', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .bottomSide img{\r\n");
      out.write("            width:55px;\r\n");
      out.write("            height:55px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right:5px;\r\n");
      out.write("            bottom:0px;\r\n");
      out.write("            display:inline-block;\r\n");
      out.write("            padding:1rem 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .heart img{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:13px;\r\n");
      out.write("            right:13px;\r\n");
      out.write("            width:40px;\r\n");
      out.write("            height:40px;\r\n");
      out.write("        }\r\n");
      out.write("         .blog{\r\n");
      out.write("            margin:0 auto;\r\n");
      out.write("            width:800px;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            background: #f9f8f3;\r\n");
      out.write("            margin-bottom:400px;\r\n");
      out.write("        } \r\n");
      out.write("        .blog .centerBox{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            padding-bottom:10px;\r\n");
      out.write("            margin:0 20px;\r\n");
      out.write("            border-bottom:1px solid #ddd;\r\n");
      out.write("        }\r\n");
      out.write("        .blog .titleBox{\r\n");
      out.write("            font-size:40px;\r\n");
      out.write("            padding:20px;\r\n");
      out.write("            margin-bottom:10px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            font-family: 'Gamja Flower', cursive;\r\n");
      out.write("        }\r\n");
      out.write("        .blog .idBox{\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("            left:0;\r\n");
      out.write("            padding-right:10px;\r\n");
      out.write("            padding-bottom:10px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            font-family: 'Patrick Hand', cursive;\r\n");
      out.write("        }\r\n");
      out.write("        .blog .dateBox{\r\n");
      out.write("            font-size:13px;\r\n");
      out.write("            right:0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            padding-left:5px;\r\n");
      out.write("            color:#878484;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding-bottom:5px;\r\n");
      out.write("            font-family: 'Lisu Bosa', serif;\r\n");
      out.write("        }\r\n");
      out.write("        .blog .bcontent{\r\n");
      out.write("            padding:20px;\r\n");
      out.write("            padding-top:40px;\r\n");
      out.write("            font-family: 'Poor Story', cursive;\r\n");
      out.write("        }\r\n");
      out.write("        .topBox .logo{\r\n");
      out.write("            width:120px;\r\n");
      out.write("            padding-left:20px;\r\n");
      out.write("            padding-top: 30px;\r\n");
      out.write("            margin-bottom:-15px;\r\n");
      out.write("        }\r\n");
      out.write("        .user{\r\n");
      out.write("            width:23px;\r\n");
      out.write("            height:23px;\r\n");
      out.write("            padding-right:10px;\r\n");
      out.write("            padding-left:3px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .slide{\r\n");
      out.write("            color:#878484;\r\n");
      out.write("            font-size:17px;\r\n");
      out.write("        }\r\n");
      out.write("        .subcenterBox{\r\n");
      out.write("        	display:flex;\r\n");
      out.write("        }\r\n");
      out.write("        .menu ::before{\r\n");
      out.write("		    font-family: 'Material Icons';\r\n");
      out.write("		    font-size: 1.5em;\r\n");
      out.write("		    float: left;\r\n");
      out.write("		    clear: left;\r\n");
      out.write("		}\r\n");
      out.write("		.menu label::before{ content: '\\e5d2'; }\r\n");
      out.write("		.menu li:nth-child(1) a::before{ content: '\\e745'; }\r\n");
      out.write("		.menu li:nth-child(2) a::before{ content: '\\e872'; }\r\n");
      out.write("		#expand-menu { /* 체크박스 폼 요소 감춤 */\r\n");
      out.write("		    display: none;\r\n");
      out.write("		}\r\n");
      out.write("		#expand-menu:checked ~ ul { /* 체크박스 체크되었으면 메뉴 목록 표시 - 반응형 표시용 */\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    height: auto;\r\n");
      out.write("		}\r\n");
      out.write("		.menu {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    width: 30px;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("		    border-radius: 5px;\r\n");
      out.write("		    padding: 5px;\r\n");
      out.write("		    box-sizing: border-box;\r\n");
      out.write("		    overflow: hidden; /* 반응형 애니메이션용 */\r\n");
      out.write("		    transition: all 0.5s ease; /* 반응형 애니메이션 */\r\n");
      out.write("		    float:right;\r\n");
      out.write("        	margin-right:10px;\r\n");
      out.write("        	font-size:10px;\r\n");
      out.write("        	margin-top: -35px;\r\n");
      out.write("    		margin-right: 20px;\r\n");
      out.write("        	padding-top:10px;\r\n");
      out.write("		}\r\n");
      out.write("		.menu ul {\r\n");
      out.write("		    list-style: none;\r\n");
      out.write("		    margin: 0;\r\n");
      out.write("		    padding: 0;\r\n");
      out.write("		}\r\n");
      out.write("		.menu a, .menu > label {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    height: 20px;\r\n");
      out.write("		    padding: 4px;\r\n");
      out.write("		    cursor: pointer;\r\n");
      out.write("		    color: #000;\r\n");
      out.write("		    text-decoration: none;\r\n");
      out.write("		    padding-top:3px;\r\n");
      out.write("		}\r\n");
      out.write("		.menu:hover {\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("		    width:70px;\r\n");
      out.write("		}\r\n");
      out.write("		.menu ul li:hover {\r\n");
      out.write("		    background-color: #e1e1e1;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("		    border-radius: 12px;\r\n");
      out.write("		}\r\n");
      out.write("		.menu div {\r\n");
      out.write("		    position: absolute; /* 절대 위치로 텍스트 고정 */\r\n");
      out.write("		    line-height: 1.5;\r\n");
      out.write("		    font-size: 1em;\r\n");
      out.write("		    font-family: 'Noto Sans KR';\r\n");
      out.write("		    padding: 0 0 0 20px; /* 패딩 20p로 축소 */\r\n");
      out.write("		}\r\n");
      out.write("		@media screen and (max-width:1023px) {\r\n");
      out.write("		    .menu { /* 1단계 */\r\n");
      out.write("		        width: 30px;\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("		.menu #expand-menu:not(:checked) ~ ul { /* 데스크탑 화면에서도 메뉴를 접었더 펼칠 수 있음 */\r\n");
      out.write("		    display: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.lineBox {\r\n");
      out.write("		  display: flex;\r\n");
      out.write("		  margin-bottom: 50px;\r\n");
      out.write("		  gap: 20px;\r\n");
      out.write("		  width: 100%;\r\n");
      out.write("		  height: 350px;\r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    	function getInfoPage(param){\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("    			dataType : \"text\",\r\n");
      out.write("    			type : \"POST\",\r\n");
      out.write("    			url : \"/infoPage\",\r\n");
      out.write("    			data : {\r\n");
      out.write("    				\"seq\" : param\r\n");
      out.write("    			},success : function(result) {\r\n");
      out.write("    				$('#realBox').css({\r\n");
      out.write("    					'display' : 'none'\r\n");
      out.write("    				})\r\n");
      out.write("    				$('.toptitle').css({\r\n");
      out.write("    					'display' : 'none'\r\n");
      out.write("    				})\r\n");
      out.write("    				$('.blog').css({\r\n");
      out.write("    					'display' : 'block'\r\n");
      out.write("    				})\r\n");
      out.write("    				var obj = result.split(\"^\")				\r\n");
      out.write("    				$('.idBox').text(obj[0])\r\n");
      out.write("    				//obj[0] : 아이디\r\n");
      out.write("    				$('.titleBox').text(obj[1])\r\n");
      out.write("    				//obj[1] : 제목\r\n");
      out.write("    				$('.dateBox').text(obj[2])\r\n");
      out.write("    				$('#resultSeq').val(param)\r\n");
      out.write("    				$('#rSeq').val(param)    				\r\n");
      out.write("\r\n");
      out.write("    				//obj[2] : 작성한날짜\r\n");
      out.write("    				document.getElementById(\"realBori\").innerHTML = obj[3];\r\n");
      out.write("    				//obj[3] : 컨텐트내용\r\n");
      out.write("    			}\r\n");
      out.write("    		})\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	function deleteB(){\r\n");
      out.write("    		$(\"#deleteBtn\").submit();\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	function editB(){\r\n");
      out.write("    		$(\"#editBtn\").submit();    		\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 class='toptitle'>블로그 보기</h1>\r\n");
      out.write("		\r\n");
      out.write("	   <a class=\"\" href=\"goBlog\">블로그 작성</a>\r\n");
      out.write("\r\n");
      out.write("       <div class=\"flex_column\" id='realBox'>\r\n");
      out.write("        <div class=\"lineBox\">\r\n");
      out.write("            <!--4개 반복-->\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("<!--4개 반복-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"lineBox\">\r\n");
      out.write("            <!--4개 반복-->\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("<!--4개 반복-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"lineBox\">\r\n");
      out.write("            <!--4개 반복-->\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("<!--4개 반복-->\r\n");
      out.write("           <div class=\"parent-container\">  <a class=\"main\" href=\"/\">메인 ^^</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class='blog' style=\"display:none\">\r\n");
      out.write("        <div class=\"topBox\">\r\n");
      out.write("            <img class=\"logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/noticeimg/logo.png\">\r\n");
      out.write("            <div class=\"titleBox\">나는 가만히 있는 게 내 일인데</div>\r\n");
      out.write("            <div class=\"centerBox\">\r\n");
      out.write("	            <div class=\"subcenterBox\">\r\n");
      out.write("	                <img class=\"user\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon/profile-user.png\">\r\n");
      out.write("	                <div class=\"idBox\">bori</div>\r\n");
      out.write("	                <div class=\"slide\">></div>\r\n");
      out.write("	                <div class=\"dateBox\">2023.07.31</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                <div class=\"menu\">\r\n");
      out.write("	                <label for=\"expand-menu\"></label>\r\n");
      out.write("	                <input type=\"checkbox\" id=\"expand-menu\" name=\"expand-menu\">\r\n");
      out.write("	                <ul>\r\n");
      out.write("		                <li><a href=\"#\" class=\"item\" onclick=\"editB()\">수정</a></li>\r\n");
      out.write("		           		<li><a href=\"#\" class=\"item\" onclick=\"deleteB()\">삭제</a></li>                    \r\n");
      out.write("	                </ul>\r\n");
      out.write("	                <form action=\"/editBlog\" method=\"POST\" id=\"editBtn\">\r\n");
      out.write("	                	<input type=\"hidden\" value=\"\" name=\"seq\" id='rSeq'>\r\n");
      out.write("	                </form>\r\n");
      out.write("	                <form action=\"/deleteBlog\" method=\"POST\" id=\"deleteBtn\">\r\n");
      out.write("		                <input type=\"hidden\" value=\"\" name=\"seq\" id='resultSeq'>	             \r\n");
      out.write("		            </form>	\r\n");
      out.write("	            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bcontent\" id='realBori'>\r\n");
      out.write("            제주도에 놀러왔다!!\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/blog/toolBlog1.jsp(364,11) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/blog/toolBlog1.jsp(364,11) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(3);
      // /WEB-INF/views/blog/toolBlog1.jsp(364,11) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(1);
      // /WEB-INF/views/blog/toolBlog1.jsp(364,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      // /WEB-INF/views/blog/toolBlog1.jsp(364,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blog/toolBlog1.jsp(364,11) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<div class=\"itemBox\" onclick=\"getInfoPage('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getSeq()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">\r\n");
            out.write("                    <div class=\"topSide\">\r\n");
            out.write("                        <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getBimgpath()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("                        <div class=\"heart\">\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/icon/heart.png\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"bottomSide\">\r\n");
            out.write("                            <div class=\"title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"id\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getWritedate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/icon/arrow.png\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/blog/toolBlog1.jsp(384,11) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(4);
      // /WEB-INF/views/blog/toolBlog1.jsp(384,11) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(7);
      // /WEB-INF/views/blog/toolBlog1.jsp(384,11) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setStep(1);
      // /WEB-INF/views/blog/toolBlog1.jsp(384,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("vo");
      // /WEB-INF/views/blog/toolBlog1.jsp(384,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blog/toolBlog1.jsp(384,11) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<div class=\"itemBox\" onclick=\"getInfoPage('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getSeq()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">\r\n");
            out.write("                    <div class=\"topSide\">\r\n");
            out.write("                        <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getBimgpath()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("                        <div class=\"heart\">\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/icon/heart.png\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"bottomSide\">\r\n");
            out.write("                            <div class=\"title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"id\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getWritedate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/icon/arrow.png\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/blog/toolBlog1.jsp(404,11) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(8);
      // /WEB-INF/views/blog/toolBlog1.jsp(404,11) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(11);
      // /WEB-INF/views/blog/toolBlog1.jsp(404,11) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setStep(1);
      // /WEB-INF/views/blog/toolBlog1.jsp(404,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("vo");
      // /WEB-INF/views/blog/toolBlog1.jsp(404,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blog/toolBlog1.jsp(404,11) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<div class=\"itemBox\" onclick=\"getInfoPage('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getSeq()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">\r\n");
            out.write("                    <div class=\"topSide\">\r\n");
            out.write("                        <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getBimgpath()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("                        <div class=\"heart\">\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/icon/heart.png\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"bottomSide\">\r\n");
            out.write("                            <div class=\"title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"id\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.getWritedate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/icon/arrow.png\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
